#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-shapely
Version  : 2.0.0
Release  : 42
URL      : https://files.pythonhosted.org/packages/61/76/6e635cc4ba33e8c170ef5934dad5c269dc5cb9607e878efb2aba12f78361/shapely-2.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/61/76/6e635cc4ba33e8c170ef5934dad5c269dc5cb9607e878efb2aba12f78361/shapely-2.0.0.tar.gz
Summary  : Manipulation and analysis of geometric objects
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-shapely-filemap = %{version}-%{release}
Requires: pypi-shapely-lib = %{version}-%{release}
Requires: pypi-shapely-python = %{version}-%{release}
Requires: pypi-shapely-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : geos-dev
BuildRequires : pypi(cython)
BuildRequires : pypi(numpy)
BuildRequires : pypi(setuptools)

%description
=======
Shapely
=======
.. Documentation at RTD — https://readthedocs.org
.. image:: https://readthedocs.org/projects/shapely/badge/?version=stable
:alt: Documentation Status
:target: https://shapely.readthedocs.io/en/stable/

%package filemap
Summary: filemap components for the pypi-shapely package.
Group: Default

%description filemap
filemap components for the pypi-shapely package.


%package lib
Summary: lib components for the pypi-shapely package.
Group: Libraries
Requires: pypi-shapely-filemap = %{version}-%{release}

%description lib
lib components for the pypi-shapely package.


%package python
Summary: python components for the pypi-shapely package.
Group: Default
Requires: pypi-shapely-python3 = %{version}-%{release}

%description python
python components for the pypi-shapely package.


%package python3
Summary: python3 components for the pypi-shapely package.
Group: Default
Requires: pypi-shapely-filemap = %{version}-%{release}
Requires: python3-core
Provides: pypi(shapely)
Requires: pypi(numpy)

%description python3
python3 components for the pypi-shapely package.


%prep
%setup -q -n shapely-2.0.0
cd %{_builddir}/shapely-2.0.0
pushd ..
cp -a shapely-2.0.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1670884098
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-pypi-shapely

%files lib
%defattr(-,root,root,-)
/usr/share/clear/optimized-elf/other*

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
