#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Shapely
Version  : 1.8.0
Release  : 27
URL      : https://files.pythonhosted.org/packages/1c/0c/454c80f71bd5ece52fb06d2905bf956b9122f4be539d5ae5df4b10dd3e14/Shapely-1.8.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/1c/0c/454c80f71bd5ece52fb06d2905bf956b9122f4be539d5ae5df4b10dd3e14/Shapely-1.8.0.tar.gz
Summary  : Geometric objects, predicates, and operations
Group    : Development/Tools
License  : BSD-3-Clause
Requires: Shapely-license = %{version}-%{release}
Requires: Shapely-python = %{version}-%{release}
Requires: Shapely-python3 = %{version}-%{release}
Requires: numpy
BuildRequires : buildreq-distutils3
BuildRequires : geos-dev
BuildRequires : numpy
BuildRequires : python3-dev

%description
Shapely
        =======
        
        |github-actions| |appveyor| |coveralls|

%package license
Summary: license components for the Shapely package.
Group: Default

%description license
license components for the Shapely package.


%package python
Summary: python components for the Shapely package.
Group: Default
Requires: Shapely-python3 = %{version}-%{release}
Provides: shapely-python

%description python
python components for the Shapely package.


%package python3
Summary: python3 components for the Shapely package.
Group: Default
Requires: python3-core
Provides: pypi(shapely)

%description python3
python3 components for the Shapely package.


%prep
%setup -q -n Shapely-1.8.0
cd %{_builddir}/Shapely-1.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1636417262
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/Shapely
cp %{_builddir}/Shapely-1.8.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/Shapely/eb14a25dd1cea155c4fa3e201dd54eee8bbb62eb
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/Shapely/eb14a25dd1cea155c4fa3e201dd54eee8bbb62eb

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
